name: Java CI with Gradle

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure gradle
        run: ./gradlew

      - name: Check for license headers
        run: ./gradlew checkLicenses

      - name: Build with Gradle
        run: ./gradlew build -x javadoc -x test --full-stacktrace

      - name: Build Javadocs
        run: ./gradlew javadoc
